# Generated by Django 4.2.13 on 2024-06-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='outfits/')),
                ('main_color', models.CharField(max_length=20)),
                ('outfit_type', models.CharField(choices=[('casual', 'Casual'), ('professional', 'Professional')], default='casual', max_length=15)),
                ('color_one', models.CharField(default='black', max_length=20)),
                ('color_two', models.CharField(default='white', max_length=20)),
            ],
        ),
    ]
